### ISSUE TITLE
Exception on destroying a group

### ISSUE THREAD

**Issue by mihir3535** [rhgrant10/Groupy#11]
Hi, while playing around with the library, I get the following stack trace
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/groupy/api/endpoint.py", line 56, in response
    data = r.json()
  File "/usr/local/lib/python3.4/site-packages/requests/models.py", line 763, in json
    return json.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/groupy/object/responses.py", line 222, in destroy
    endpoint.Groups.destroy(self.group_id)
  File "/usr/local/lib/python3.4/site-packages/groupy/api/endpoint.py", line 176, in destroy
    return cls.response(r)
  File "/usr/local/lib/python3.4/site-packages/groupy/api/endpoint.py", line 58, in response
    raise errors.ApiError(r)
groupy.api.errors.ApiError: <Response [200]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mihirjoshi/PycharmProjects/pyGroupMe/AppModel.py", line 60, in <module>
    main()
  File "/Users/mihirjoshi/PycharmProjects/pyGroupMe/AppModel.py", line 56, in main
    group.destroy()
  File "/usr/local/lib/python3.4/site-packages/groupy/object/responses.py", line 223, in destroy
    except errors.ApiErrorError as e:
AttributeError: 'module' object has no attribute 'ApiErrorError'
```

when trying to remove a group with the following code:

```python
Group.create("test group")
sleep(10) # Just a delay so I can check groupme.com to make sure group was made
for group in Group.list().filter(name__contains='test'):
    group.destroy()
```

I'm a novice to Python so I may have done something wrong, but the group is successfully deleted. I just get that exception raised for some reason.

**Comment by rhgrant10** [comment]
Yeah it looks like a copy/paste error during some refactoring. It was fixed in 51b837759d7b5bd6b1fe265623f2c964f83d6ce4, which has been included in the [v0.6.3, the latest PyPI release](https://pypi.python.org/pypi?:action=display&name=GroupyAPI&version=0.6.3).
