### ISSUE TITLE
authorization error.. anyone else?

### ISSUE THREAD

**Issue by xac1d** [rhgrant10/Groupy#42]
sorry i understand this is for issues and not support. i installed the latest today but i seem to be getting 401 auth errors from the api. 

`[ec2-user@ip-172-31-22-33 groupme]$ python36 g.py
received a bad response
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/groupy/session.py", line 28, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.groupme.com/v3/users/me
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/groupy/session.py", line 28, in request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.groupme.com/v3/users/me

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "g.py", line 7, in <module>
    print (client.user.get_me())
  File "/usr/local/lib64/python3.6/site-packages/groupy/api/user.py", line 27, in get_me
    response = self.session.get(url)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/groupy/session.py", line 32, in request
    raise exceptions.BadResponse(response) from e
groupy.exceptions.BadResponse: HTTP 401: unauthorized
`
the scrip is very simple to start:

`from groupy.client import Client

key = 'token_from_groupme'
client = Client.from_token(key)

for group in client.groups.list():
	print (group.name)`

**Comment by rhgrant10** [comment]
Hey, no worries - feel free to create issues when you have problems :) In this case, however, I'm unable to replicate your problem...

```
In [1]: import groupy

In [2]: client = groupy.Client.from_token('mytoken')

In [3]: print(client.user.get_me())
{'created_at': 1381863553, 'email': 'rhgrant10@gmail.com', 'facebook_connected': False, 'id': '12345678', 'image_url': 'http://i.groupme.com/c74fa32017f90131c6cf3671e9653186', 'locale': 'en_us', 'name': 'Robert Grant', 'phone_number': '+1 555SHOE', 'sms': False, 'twitter_connected': False, 'updated_at': 1511845133, 'user_id': '12345678', 'zip_code': None, 'share_url': None, 'share_qr_code_url': None, 'tags': ['phone-us']}
```

Are you sure your token is correct? I've run into issues reading it from a file in the past simply because many text editors will automatically append a newline to a file when you save it.

**Comment by xac1d** [comment]
whoops my fault, i was using the bot id instead of the access token. thanks, working now!
